DROP TABLE tells CASCADE;
DROP TABLE visitors CASCADE;

CREATE TABLE tells (
  tid SERIAL PRIMARY KEY,
  question VARCHAR(280) NOT NULL,
  answer VARCHAR(1000),
  answered BOOLEAN DEFAULT FALSE,
  likes INTEGER DEFAULT 0, 
  date_asked TIMESTAMP DEFAULT NOW(),
  date_answered TIMESTAMP
);

CREATE TABLE visitors (
  vid SERIAL PRIMARY KEY,
  key VARCHAR(20)
);